### ISSUE TITLE
Game keeps crashing from using stacked armor trims.

### ISSUE THREAD

**Issue by Lovee101** [ApfelRauber/StackedTrims#3]
The game crashed whilst container click Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3767()" because "de.seiboldsmuehle.stacked_trims.ServerTickListener.currentServer" is null 

Every time I try to drag the amour trims into the smiting table with my amour the game crashes, yet the mod works fine for my boyfriend since we are playing together in a Minecraft moded world

---- Minecraft Crash Report ----

// You should try our sister game, Minceraft!

Time: 2023-07-11 00:44:00
Description: Container click

java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3767()" because "de.seiboldsmuehle.stacked_trims.ServerTickListener.currentServer" is null
	at net.minecraft.class_8053.handler$chb000$stacked_trims$apply(class_8053.java:1029)
	at net.minecraft.class_8053.method_48429(class_8053.java:96)
	at net.minecraft.class_8062.method_8116(class_8062.java:62)
	at net.minecraft.class_4862.method_24928(class_4862.java:100)
	at net.minecraft.class_4861.method_7609(class_4861.java:106)
	at net.minecraft.class_4861$3.method_5431(class_4861.java:96)
	at net.minecraft.class_1277.redirect$bhe000$fabric-transfer-api-v1$fabric_redirectMarkDirty(class_1277.java:543)
	at net.minecraft.class_1277.method_5447(class_1277.java:144)
	at net.minecraft.class_1735.method_7673(class_1735.java:72)
	at net.minecraft.class_1735.method_48931(class_1735.java:63)
	at net.minecraft.class_1703.method_7616(class_1703.java:660)
	at net.minecraft.class_4861.method_7601(class_4861.java:147)
	at net.minecraft.class_1703.method_30010(class_1703.java:394)
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_636.method_2906(class_636.java:450)
	at net.minecraft.class_465.method_2383(class_465.java:548)
	at net.minecraft.class_465.method_25402(class_465.java:340)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_8053.handler$chb000$stacked_trims$apply(class_8053.java:1029)
	at net.minecraft.class_8053.method_48429(class_8053.java:96)
	at net.minecraft.class_8062.method_8116(class_8062.java:62)
	at net.minecraft.class_4862.method_24928(class_4862.java:100)
	at net.minecraft.class_4861.method_7609(class_4861.java:106)
	at net.minecraft.class_4861$3.method_5431(class_4861.java:96)
	at net.minecraft.class_1277.redirect$bhe000$fabric-transfer-api-v1$fabric_redirectMarkDirty(class_1277.java:543)
	at net.minecraft.class_1277.method_5447(class_1277.java:144)
	at net.minecraft.class_1735.method_7673(class_1735.java:72)
	at net.minecraft.class_1735.method_48931(class_1735.java:63)
	at net.minecraft.class_1703.method_7616(class_1703.java:660)
	at net.minecraft.class_4861.method_7601(class_4861.java:147)
	at net.minecraft.class_1703.method_30010(class_1703.java:394)
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_636.method_2906(class_636.java:450)
	at net.minecraft.class_465.method_2383(class_465.java:548)
	at net.minecraft.class_465.method_25402(class_465.java:340)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)

-- Click info --
Details:
	Menu Type: minecraft:smithing
	Menu Class: net.minecraft.class_4862
	Slot Count: 40
	Slot: 37
	Button: 0
	Type: QUICK_MOVE
Stacktrace:
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_636.method_2906(class_636.java:450)
	at net.minecraft.class_465.method_2383(class_465.java:548)
	at net.minecraft.class_465.method_25402(class_465.java:340)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_4895
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 2 total; [class_746['anoid_'/5839, l='ClientLevel', x=894.95, y=55.00, z=4292.39], class_745['itsfireboi500'/149, l='ClientLevel', x=898.98, y=55.00, z=4290.37]]
	Chunk stats: 4096, 1529
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,0), Section: (at 0,0,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2011237 game time, 2473679 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Supplementaries Generated Pack, essential

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 940845712 bytes (897 MiB) / 1744830464 bytes (1664 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=31.0.12044.3
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 19885.34
	Virtual memory used (MB): 12863.73
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 218.11
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		allthetrims: AllTheTrims 3.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		appleskin: AppleSkin 2.5.0+mc1.20
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
		architectury: Architectury 9.0.8
		bettertrims: bettertrims 1.0.3
		cardinal-components: Cardinal Components API 5.2.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-block: Cardinal Components API (blocks) 5.2.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
			cardinal-components-level: Cardinal Components API (world saves) 5.2.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.1
			cardinal-components-world: Cardinal Components API (worlds) 5.2.1
		carryon: Carry On 2.1.1.2
			amecsapi: Amecs API 1.5.0+mc1.20-pre1
		collective: Collective 6.62
		cosmetica: Cosmetica 1.2.5+hotfix
			com_github_cosmetica-cc_cosmeticadotjava: CosmeticaDotJava 1.11.2
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a27
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d27
			sulphate: Sulfate 1.1.1
		cristellib: Cristel Lib 1.1.0
			blue_endless_jankson: jankson 1.2.1
		durabilityviewer: Giselbaers Durability Viewer 1.20-fabric0.83.0-1.10.5
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.4+1.20
		elementa: Elementa 590
		elytraslot: Elytra Slot 6.3.0+1.20.1
		essential: Essential 12933+deploy-staging+gf941de5ac
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.0
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.6
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.7
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.7
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.6
		fabric-api: Fabric API 0.84.0+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b77
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.9.5+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fallingtree: FallingTree 4.2.0
		geodes: More Geodes 1.8.2
		grindenchantments: Grind Enchantments 3.1.2+1.20
			codec-config-api: Codec Config API 1.0.2+1.19.3
		handcrafted: Handcrafted 2.3.2
		indium: Indium 1.0.20+mc1.20.1
		infinitetrading: Infinite Trading 4.0
		inventorysorter: Inventory Sorter 1.9.0-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		inventorytotem: Inventory Totem 3.0
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 11.1.4
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.11
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.1+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		mine_treasure_mr: Mine Treasure 1.2.9
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.6.1
		org_jetbrains_annotations: annotations 13.0
		piercingpaxels: piercingpaxels 1.0.11
		plentyofarmors: Plenty Of Armors 1.2.1
		resourcefullib: Resourceful Lib 2.1.1
			com_teamresourceful_yabn: yabn 1.0.3
		roughlyenoughitems: Roughly Enough Items 12.0.626
			error_notifier: Error Notifier 1.0.9
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		sodium: Sodium 0.4.10+build.27
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.1.1
		stacked_trims: Stacked Trims 1.0.0
		supplementaries: Supplementaries 1.20-2.5.18
		t_and_t: Towns and Towers 1.10.2
		taxfreelevels: Tax Free Levels 1.3.3
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.1
		trinkets: Trinkets 3.7.0
		universalcraft: UniversalCraft 277
		vigilance: Vigilance 284
		villagerleads: VillagerLeads 0.0.1
		voidtotem: Void Totem 3.0.1
		windchimes: Windchimes 1.2.3+1.20
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.21-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 3.2.0 Core Profile Context 22.20.44.221025, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, Supplementaries Generated Pack
	Current Language: en_us
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx

**Comment by ApfelRauber** [comment]
Fixed! Thanks for the report!
